### ISSUE TITLE
Replace BellState by BellIndex

### ISSUE THREAD

**Issue by GuusAvis** [SoftwareQuTech/QLink-Interface#5]
Replace the BellState that is defined in this module by `netsquid.qubits.ketstates.BellIndex`.

**Comment by GuusAvis** [comment]
@AckslD should this actually happen, or do you want to keep QLink-Interface independent from NetSquid? Otherwise, I'll convert between BellState and BellIndex in the magic link layer.

**Comment by AckslD** [comment]
@GuusAvis, yeah indeed the intention is to keep it independent from netsquid
